### ISSUE TITLE
on.emit cannot emit a window event

### ISSUE THREAD

**Issue by ghost** [dojo/core#101]
on.emit(window, 'resize', callback); would cause a exception while check the target.ownerDocument

**Comment by kitsonk** [comment]
It doesn't actually cause an exception, because target.ownerDocument will returned undefined and before the patch, it tool the sythentic emitter path and complained that `window` was not an event emitter (which it is).  It appears that the code wouldn't properly handle `document` either (because `document.ownerDocument` returns `null`)

The fix I supplied now handles both of them properly (it uses `window.document` to create the event, since IE doesn't have the `Event()` constructor and we need something that can create the event).
