### ISSUE TITLE
Type has.add better...

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#117]
The typing of has.add [could be improved](https://github.com/dojo/core/blob/e97df0969f543b4c922b433e5c0d292edba452c5/src/has.ts#L17).

We could have something more like:

``` typescript
export type HasTest = boolean | string | number | (() => boolean | string | number);
export function add(feature: string, value: HasTest, overwrite?: boolean): void { }
```

Also, was there reasoning in not passing in the global, document, element arguments to a test function?

**Comment by kfranqueiro** [comment]
RE typing `has.add` (and the return value of `has`, I suppose) more specificially, I suspect we originally didn't want to prematurely restrict the types of values of has features, but AFAICT in Dojo 1 (at least looking at Dojo and Dijit), everything is or resolves to one of those three primitive types (some return undefined in some cases, but would probably be more appropriately a boolean or number in those cases as well).

RE your last question, from the proposal:

> Nothing is passed to deferred feature tests because developers can get references to the global and document themselves and can create a test element on their own

Also there's the potential gotcha in `has` in Dojo 1 that the test element is shared, so you have to clean up anything you did to it in your test or risk messing up other subsequently-run tests.

**Comment by kitsonk** [comment]
> I suspect we originally didn't want to prematurely restrict the types of values of has features

I would argue that we should restrict to those three primitives.  My initial feeling was that it should be strict boolean, because anything else would promote usage of feature detection in the wrong way.  We have already been trying to eradicate any concept of UA sniffing.  My thoughts would be that if you need more rich return values, you shouldn't be using the `has` API.

As far as not passing anything, that makes sense.  The only argument I would have, is that passing the reference to global might make sense, in that you would promote self contained functions that could be portable without having to worry about other imports or strict mode.

**Comment by devpaul** [comment]
> I would argue that we should restrict to those three primitives.

I agree, by limiting the library we improve the intended use case.

>  We have already been trying to eradicate any concept of UA sniffing.

I think we've learned that if UA sniffing is necessary to detect a feature that is is better placed behind a flag denoting the feature rather than using UA sniffing directly in code.

> passing the reference to global might make sense

I lean toward not passing anything to maintain API simplicity. A developer can get access to global by importing `core/global`.

I noticed that we allow `add()` to silently return when a feature has already been implemented. This can potentially lead to a lot of frustration if tests are not added, especially because `testFunctions` is not exported. To solve this what if we supplied an `exists(feature: string): boolean` method and did not export `cache`? Also, we shouldn't silently fail to add a test. We should throw or otherwise notify the caller that add failed; i.e. by returning a boolean. Also, since we're looking at the has API, what do you think about removing the `overwrite` parameter from `has.add()` and create a `has.set()` method that will always overwrite an existing feature?
