### ISSUE TITLE
is defer or Deferred missing?

### ISSUE THREAD

**Issue by taoqf** [dojo/core#142]
i cannot find Deferred which is in dojo 1.x or defer() in bluebird,
it is very useful especially when i want resolve it some times later in other places.

**Comment by dylans** [comment]
@taoqf I think async/Task solves the use case of Deferred for cancellation/resolution. Please take a look at the source for request to see how we use it, and let us know if this provides what you need from Deferred.

**Comment by taoqf** [comment]
i have had a look at requst.ts and async/task.ts, but i can not find any clew yet.
i would have a resolver in f1, and would resolve/reject in f2.like this:
`function f1(){`
`return defer();`
`}`
`function f2(resolver){`
`resolver.resolve();`
`}`

**Comment by kitsonk** [comment]
In your example, you never invoke `f1`.

If you need a reference to the `resolver` you should grab it from within the executor.  If all you want is a `Promise` that is already resolved, you should use `Promise.resolve()`.

What is a specific use case you are trying to accomplish?

**Comment by taoqf** [comment]
what if i use it like this:

```
function f3(){
let r = f1();
setTimeout(()=>{
f2(r);
}, 1);
}
```

sorry for my terrible english.

**Comment by kitsonk** [comment]
Because the Promise specification, including what was implemented into ES6 does not expose a resolver or rejector outside of the executor, we have followed that pattern.  As @dylans mentioned, we see a use case where you want to be able to cancel a "promise" therefore we have provided `Task` which exposes a `.cancel()` method.

Because Dojo 1 had the Deferred API before there was a Promise API, we kept it to be backwards compatible.  Dojo 2, we would rather adopt the modern patterns.  It would be better to adopt this pattern yourself.  If you really want a promise decorated with its resolver, you can do that yourself, for example:

``` javascript
function createResolvablePromise(executor) {
    let resolve, reject;
    const p = new Promise(function (_resolve, _reject) {
        resolve = _resolve;
        reject = _reject;
        executor && executor(resolve, reject);
    });
    p.resolve = resolve;
    p.reject = reject;
    return p;
}

const resolveable = createResolvablePromise();
setTimeout(() => {
    resolveable.resolve('foo');
}, 10);

resolveable.then((value) => {
    console.log(value);
});
```

**Comment by taoqf** [comment]
thank kitsonk and dyland, i guess this would resolve my problem.
by the way, i have seen this in api of [bluebird](http://bluebirdjs.com/docs/api/deferred-migration.html).
i do need  to creat a promise in f1, but i just cannot resolve the promise in f1 which i just can give it a delay to reject.
i will resolve or reject the promise in f2 which is base on an async message from network message.
so i guess the deferred is the best way to resolve my problem.
any way, many thanks.
