### ISSUE TITLE
Can't extend Promise / overwrite .then because of private

### ISSUE THREAD

**Issue by sebilasse** [dojo/core#164]
I would like to extend _Promise.ts_ in TS.
When I want to overwrite/extend `then`, TS complains that `this.promise.then` is a `private` 
in Promise.ts [ line 403 ].

Could this become `protected` ?

**Comment by kitsonk** [comment]
The shim provided replicates the functionality in ES6 environments.  In particular the bit of code replicates the functionality described in specification of [PerformPromiseThen](http://www.ecma-international.org/ecma-262/6.0/#sec-performpromisethen).

How specifically would you plan on extending this, because it would likely cause you more harm down the road.  In fact, we may revisit the way we are polyfilling this and do like we have with other polyfills and just return the native implementation when present.

**Comment by sebilasse** [comment]
@kitsonk The native ES6 promise lets me extend `.then` – it's just about the TS error 
[edit: inbetween this made some things clear to me: https://yakovfain.com/2015/06/30/the-private-in-typescript-is-kinda-private/ ] : 

I plan to extend `.then` in two different ways (anything here currently is "IOC"):
1) When I start a promise with my `redaktor.task(id: string)` I'd like to register all the following functions in a "central registry" so that I can replay the task ...
2) basically it should make sure that everything within `.then` passes a `redaktor.data` container class which can "decide" much things and always return an object where data from users functions is optionally  stored at a named property and ".value" always returns the last return. The 2) is not so important because I could write it like `.then(R.do(function(success){}, function(error){}))`

**Comment by kitsonk** [comment]
Issue moved to [dojo/shim #30](https://github.com/dojo/shim/issues/30) via [**ZenHub**](https://www.zenhub.com/)
