### ISSUE TITLE
Immutable and Iterator Compatibility

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#169]
For some reason, the `Iterator` interfaces between our polyfills and Immutable.js doesn't seem to work together... for example, I get a design time error with something like this, but at run-time (even on IE10) it works perfectly fine:

``` typescript
import { Map } from 'immutable/immutable';
import { from as arrayFrom } from 'dojo-core/array';

const map = Map().set('foo', {});
const keys = arrayFrom(map.keys()); // Argument of type 'Iterator<string>' is not assignable to parameter of type 'Iterable<{}> | ArrayLike<{}>'.
```

I am not entirely sure, but it seems that something is causing TypeScript to think that the `Iterator` interface from Immutable isn't an `Iterable`. 😞

**Comment by mwistrand** [comment]
We may want to take some time to review the places we use `Iterable` instead of `Iterator`, since those two things are not the same. `dojo-core/iterator`'s definition of `interface Iterator` is compatible with that defined by Immutable.js, but `dojo-core/iterator` defines an `Iterable` as an object with its `Symbol.iterator` property set to an `Iterator` instance. I will be the first to admit that differentiating between the two can get hairy.

**Comment by kitsonk** [comment]
Hmmm... yeah, you are right... The other challenge, with TypeScript and the whole situation is that the well-known Symbols have to come from the global `Symbol` even when you are trying to polyfill things, because of the need to be assured that the referenced symbol is the correct referenced symbol.

The good news, as I said, is that it seems to be working at run-time.

**Comment by kitsonk** [comment]
Issue moved to [dojo/shim #31](https://github.com/dojo/shim/issues/31) via [**ZenHub**](https://www.zenhub.com/)
