### ISSUE TITLE
dojo-core/load and non-AMD environments

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#201]
We likely need to enhance `dojo-core/load` so that it can load resources via other loaders (e.g. in a WebPack bundle) and have that be transparent to the end developer.

We also need to consider how `load()` would handle something that contains an AMD plugin signature, in that if it is not running under `AMD` should it try to replicate the functionality of the AMD plugin interface, loading the plugin module and executing the plugin API as specified in the AMD specification?  This feature would make it easier for end developers to potentially use AMD plugins without having to worry about where their code ends up...

**Comment by mwistrand** [comment]
Regarding an AMD-style plugin implementation, I do not think the [amdjs API](https://github.com/amdjs/amdjs-api/blob/master/LoaderPlugins.md) could be met exactly given that `@dojo/core/load` is not actually an AMD loader, but we should be able to get close:

```typescript
interface LoadPlugin<T> {
  normalize?: (resourceId: string, normalize: (resourceId: string) => string): string;
  load(resourceId: string, load: Load, resolve: (value?: T | Thenable<T>) => void): T;
}
```

Either the default export (`exports.default` in the ES5-transpiled TS) could be a `LoadPlugin` object, or the result of calling `load` would need to a `LoadPlugin` object. The optional `normalize` method would be passed the resource ID, as well as the `require.toUrl` or `require.resolve` method, depending on the environment. The required `load` method would not receive the contextual require, but would instead receive the `@dojo/core/load` method itself, along with a callback that should receive the final value.

Since there is now a [baked-in webpack-specific `load`](https://github.com/dojo/core/blob/master/src/load/webpack.ts) method, any updates to that module would be with the caveat that any value that could potentially be loaded via a plugin would need to be already included in a webpack chunk.

**Comment by dylans** [comment]
> Regarding an AMD-style plugin implementation, I do not think the amdjs API could not be met exactly given that @dojo/core/load is not actually an AMD loader

Did you mean to have a double negative here? :)

**Comment by mwistrand** [comment]
@dylans No, thanks for catching that. I meant to say that I don't believe that API can be fulfilled exactly as specified.

**Comment by mwistrand** [comment]
It is still a work in progress (e.g., `load/webpack.ts` still needs to be updated), but there is a working version [here](https://github.com/mwistrand/core/commit/c532758a6c8eedfe097a0b9264870ab2c373df55). The API is slightly different than that described above, namely in that the plugin's `load` is expected to return a promise instead of executing a callback. Initially I had included a timeout, but quickly decided against it to avoid either setting an arbitrary timeout number or requiring an options object to be passed in as well.

**Comment by mwistrand** [comment]
Allowing for AMD-style plugins in `load/webpack` is a more complicated topic since it also leaves room for webpack loaders (specifically just the [bundle loader](https://github.com/webpack/bundle-loader) for the time being), which use the same syntax. @matt-gadd may have other ideas, but one option is to treat module IDs that match the pattern `/-loader\.*!/` as webpack modules, and all others as plugins.

**Comment by matt-gadd** [comment]
I have removed the beta-blocker label from this. We do not use AMD plugins in any of our modules anyway.

**Comment by mwistrand** [comment]
@matt-gadd AMD-styles plugins are supported as of #271. At this point, as far as I am aware, this ticket remains open since it seems more-or-less open-ended.

**Comment by eheasley** [comment]
I confirmed with Matt Gad and Matt Wistrand that the original scope of this issue has been satisfied and that it is safe to close out.  Thanks!
