### ISSUE TITLE
load is incorrectly dynamically loading Promise

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#224]
In ['src/load'](https://github.com/dojo/core/blame/master/src/load.ts#L16), Promise is being mis-loaded under NodeJS.  It isn't affecting anything because there is a native Promise in the versions of NodeJS we are using, but still it is a defect.

**Comment by mwistrand** [comment]
It's actually incorrectly loading `dojo-shim/Promise` in [AMD environments](https://github.com/dojo/core/blob/master/src/load.ts#L17) as well. Since nearly all Dojo 2-supported environments have native Promise support, this is really only noticeable in IE, where the shim module is resolved asynchronously.

**Comment by kitsonk** [comment]
Actually this is a different issue (#228).
