### ISSUE TITLE
Improve request tests

### ISSUE THREAD

**Issue by bryanforbes** [dojo/core#34]
The request tests need to be improved in the following ways:
- [x] Stop shimming XMLHttpRequest
- [x] Implement an echo server:
  - [x] Proxies to Intern's server for everything except `/__echo/`
  - [x] When `/__echo/` is requested, parse the query string, headers, and (for POST and PUT) the data and echo them back in a JSON response (something like `{ query: { ... }, headers: { ... }, data: { ... } }`)
  - [x] If the `responseType` query parameter is included, send data back in the appropriate format (for instance, `responseType=document` should return HTML)
- [x] Change the intern configuration to hit the echo server
- [x] Write tests to improve coverage, including tests for different response types

**Comment by kfranqueiro** [comment]
@bryanforbes, should stuff in [dojo's tests folder](https://github.com/dojo/dojo/tree/master/tests) (e.g. the stuff under services and its setup in `dojo.intern.js`) be useful for reference for this, or does this involve a different approach?  I'm a little confused since it seems as if the service there is only set up if you're running intern-runner, not client, so does that mean that Dojo 1's request intern tests only work via runner?

I'd like to make it as clear as possible how to get started on this, given that this task is being delegated.

**Comment by bryanforbes** [comment]
Sorry that I wasn't more specific. Yes, this should follow a similar approach to what Dojo 1 does, except that implementing a bunch of services, this should only implement one service (`__echo`). The relative parts from Dojo 1 are:
- [This section](https://github.com/dojo/dojo/blob/master/tests/dojo.intern.js#L14-L28) of `dojo.intern.js` for starting the services and for configuring the proxy
- [services/main.js](https://github.com/dojo/dojo/blob/master/tests/services/main.js) to see how we're writing the server. Keep in mind that this is using `jsgi-node` for the server which is substantially different than connect or express. I don't care what the server is written in, but it'll have to handle multipart data and proxying.

**Comment by bryanforbes** [comment]
Also, using this approach, there will be two ways to run the unit tests: using the Intern runner, or starting the Intern runner with the `proxyOnly` setting and then hit the server manually (the easiest way would be to hit `run.html`).
