### ISSUE TITLE
core/aspect#on removal?

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#61]
The `on` advice is not generally recognised in AOP.  The sorts of advice that are recognised are:
- before
- after
- afterThrowing
- afterFinally
- around

Reference [Spring](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/aop.html#aop-introduction-defn) and [AspectJ](https://eclipse.org/aspectj/doc/next/progguide/semantics-advice.html).

For ordering of advice, in Spring, there is the concept of [advice ordering](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/aop.html#aop-ataspectj-advice-ordering) with the advice specifying an order value and the advice is applied lowest to highest.  AspectJ does this [via a directive](https://eclipse.org/aspectj/doc/next/adk15notebook/ataspectj-declare.html).

Therefore I don't think we should introduce `on()` advice.  It maybe worth considering the other types of advice though.

**Comment by kitsonk** [comment]
Also, I suspect this will lead to the inevitable `dojo.byId`/`dijit.byId` type confusion.

**Comment by kfranqueiro** [comment]
To be clear, `aspect.on` is identical to `aspect.after` with `receiveArguments` set to `true` in Dojo 1.

I could fathom outright removing it, given that `aspect.after` without that parameter has included the arguments array as the second parameter (after the return value) since Dojo 1.8, making `receiveArguments` far less useful.  (It's also worth noting that the internal logic of the two functions is still intertwined, and they share the same queue.)

I can definitely see the argument of overloading the word `on` getting confusing, especially since splitting out this API kind of makes it look distinctly like "events for object methods" or something.

FWIW, cujojs/meld does have the same thing: https://github.com/cujojs/meld/blob/master/docs/api.md#meldon

**Comment by kfranqueiro** [comment]
I neglected to point out that the one useful bit about `aspect.on` (or `aspect.after` with `receiveArguments` in Dojo 1) is that the return value of the original method is never affected, as opposed to `aspect.after` otherwise which will drop the old return value on the floor if you don't return one from your advising function.

**Comment by kitsonk** [comment]
I am not seeing the utility personally.  The aregument seems to be "it is more like Dojo 1" which doesn't hold up on its own.  Having something that attaches onto a method and gets called when it does isn't really AOP.  I would hope there would be other references than cujojs for `on` advice.  I have looked at a ffew other implimentations (go.aopphp.com for example) and again, there is no on (and what is there is teh return value).  Before advice allows you to meedle in the affairs of the join point before the join point is called, after allows you to meddle in the affairs of the return value, therefore if you drop it, you drop it.  If you want the arguments, you use around advice.

Even if we didn't want traditional AOP advice, I would still not want to call it `on`.  Talk about the confusion...

**Comment by kfranqueiro** [comment]
I wasn't trying to argue that it is "more" like Dojo 1, I was trying to underline the fact that it is a direct carry-over from an existing feature that was a "mode" in `aspect.after` in Dojo 1, that we decided to split out here because that seemed less awkward than controlling it via an extra flag in `after`.

I don't disagree that it is easily the least AOP-esque part of the module, and I can agree to it not being particularly useful _if_ our event solutions are appropriate for the times we would otherwise have used this.

I'm wondering whether the reason it existed to begin with was actually a hold-over from one of the common use cases of `dojo.connect`.  I will have to poke around to see how much I actually see `aspect.after` used with `receiveArguments` set.

**Comment by kitsonk** [comment]
Makes sense, if we can find a valid use case where it makes more sense to use this functionality than utilise another programming paradigm we have between "traditional" AOP or traditional `on` or whatever.  Also, as we know from Dojo 1, things are easy to add, much harder to remove when they are out in the wild.

**Comment by msssk** [comment]
I'm inclined to think we should keep `aspect.on`. I looked at Spring, AspectJ, [AspectJS](http://www.aspectjs.com/), [aspect.js](https://github.com/mgechev/aspect.js), [jsAspect](https://github.com/antivanov/jsAspect), and of course cujoJS's [meld](https://github.com/cujojs/meld).

Amongst these `on` is unique to Dojo and cujoJS. Another somewhat unique feature common to both Dojo and cujoJS is a fairly simple, user-friendly API. I typically do not support excessive sugar in APIs, preferring that they are small and concise, well-documented and clear in their purpose. It is then up to the developer to learn the APIs they use in depth so they can use them correctly.

However, I do have a pragmatic side, and I think it's winning here. AOP can be a daunting topic, and the way it works can be surprising. If, as I suspect, a lot of AOP usage is for the simplest case ("notify me when a function is executed"), then I think the `on` method is worth keeping. It requires a minimum of knowledge of AOP, borrowing from the much more widely understood concept of events, and avoids the surprise that "oh, by the way your incomplete advice discarded the data and broke original functionality".

The question then arises, where should `on` functionality be implemented? In `dojo/aspect`, or perhaps in `dojo/on`? API-wise, I could go either way - it would be a little odd in `dojo/on`, but more familiar and accessible to people unaware of AOP. However, since it is conceptually, and implementation-wise closely tied to `dojo/aspect`, and API-wise it's not uncomfortable in `dojo/aspect`, I think keeping it as a method of `dojo/aspect` is appropriate.

`afterThrowing` and `afterFinally` have historically been achieved with `around`. We could certainly add them for convenience, but given historical usage of AOP it may not be compelling to do so.

**Comment by kitsonk** [comment]
I guess my feeling is that having `dojo/on` and `dojo/aspect::on` is and could be considered another `dijit.byId`/`dojo.byId` mystery.  If we are saying the way to modify behaviour is via `dojo/aspect` and we want to keep the semantic `on` there, then we should eliminate `dojo/on`.  I don't think we want another 6 years of questions around "when do I use `dojo/aspect::on` versus `dojo/on`."

**Comment by msssk** [comment]
I am very in favor of APIs that are not confusing, and not surprising, and I think that can actually be an argument in _favor_ of `aspect's` "do something when a function is called" method being named `on`, just like `dojo/on`. They operate in different contexts, but perform a similar function:
- `dojo/on`: register a handler on an event emitter
- `aspect/on`: register a handler for a function invocation (_handler_ for the _event_ of invoking a function)

I would consider `dojo.byId/dijit.byId` an example of good, consistent API naming: two functions with a similar purpose that operate in different contexts.

If people get confused by `dojo.byId / dijit.byId` and `dojo/on / aspect.on` it's a confusion that is easily cleared up and not a notable stumbling block on the path to becoming productive with Dojo.

**Comment by taoqf** [comment]
The simplest is the best.
like jquery.

**Comment by kitsonk** [comment]
We have become dependent on this in `dojo-widgets` though the `dojo-core/on` isn't used...  I am afraid that we will have to potentially consider this for Dojo 3.  Closing...
