### ISSUE TITLE
Bugs in timeout test and status code handling

### ISSUE THREAD

**Issue by maier49** [dojo/core#64]
The timeout test is currently failing because it is resolving with a status code before the timeout error is thrown, adding a delay to the request that is greater than the duration of the timeout should resolve this. 

Additionally, xhr.ts is currently considering any status code less than 200 or greater than or equal to 400 as an error, it should be modified so that it only treats codes less than or equal to 0, or greater than or equal to 400 as errors.

**Comment by kfranqueiro** [comment]
The reason that the timeout test fails regardless is because natively setting the XHR object's `timeout` causes it to abort when it reaches that timeout, which then fires `onreadystatechange` and hits our general error handler.  Unfortunately, XHR fires `onreadystatechange` before `ontimeout`, which makes the latter basically useless for this purpose.

The only thing I've come up with so far is to try storing a Date object when we start a request with a timeout set, and compare against that if we receive a response with `0` statusCode and empty statusText to try to determine that it's a timeout error.  I'm not sure if this is entirely foolproof though.

**Comment by kfranqueiro** [comment]
I suppose another option would be to not use native `timeout` and handle aborting the request ourselves, which seems sub-optimal but at least we'd definitely know exactly when we reached a timeout, because we control it.

**Comment by kfranqueiro** [comment]
Unfortunately, the Date idea isn't panning out, specifically in IE.  Chrome and FF seem to do fine with it, but IE actually ends up computing an elapsed time a few milliseconds less than the specified timeout.  I guess we might not have a choice but to move to `setTimeout` and aborting it ourselves. :/
